### ISSUE TITLE
Failed to export project

### ISSUE THREAD

**Issue by reinildo** [gritsenko/c3_spine_plugin#25]
On Construct 3, I receive the message: Failed to export project if I chose option: Minify mode to Simple or Advanced.
If I select None as Minify mode, it compiles but when I try to run the game it crashes with the following message: Uncaught SyntaxError: Unexpected token ']'

**Comment by MikalDev** [comment]
Thanks for the bug report, the library is not configured for minification, so it's required that it's off (I'll add a note to the documentation page about this.)

In terms of the error, I will try another export and look for the error.

I assume it works ok in preview?

**Comment by reinildo** [comment]
Yes, it works on preview.
On productions it throw this error:  `Uncaught SyntaxError: Unexpected token ']'`

Thanks for the great work. You're awesome.

**Comment by MikalDev** [comment]
Please try the latest version (1.9.0). If it works, please close this issue.

I changed the spine-webgl.js script to export as an external runtime script, instead of adding it to the C3 DOM script. I think there were recent changes (perhaps with the problematic closure compiler update) which changed how scripts could be added. This is also better in terms of one day enabling worker mode.

**Comment by reinildo** [comment]
It works like a charm. Thanks a lot.
